Table merged_table_admission_day {
  subject_id        integer    [pk]                             // کلید بیمار
  hadm_id           integer    [pk]                             // کلید بستری بیمار
  day_index         integer    [pk, note: 'شاخص روز در بستری (از روز اول: 0)']

  admittime            datetime   [note: 'from admissions']
  dischtime            datetime   [note: 'from admissions']
  deathtime            datetime   [note: 'from admissions']
  admission_type       varchar    [note: 'from admissions']
  admit_provider_id    varchar    [note: 'from admissions']
  admission_location   varchar    [note: 'from admissions']
  discharge_location   varchar    [note: 'from admissions']
  insurance            varchar    [note: 'from admissions']
  language             varchar    [note: 'from admissions']
  marital_status       varchar    [note: 'from admissions']
  race                 varchar    [note: 'from admissions']
  edregtime            datetime   [note: 'from admissions']
  edouttime            datetime   [note: 'from admissions']
  hospital_expire_flag integer    [note: 'from admissions']

  stay_id               integer  [note: 'from icustays']
  first_careunit        varchar  [note: 'from icustays']
  last_careunit         varchar  [note: 'from icustays']
  icustays_intime       datetime [note: 'from icustays']
  icustays_outtime      datetime [note: 'from icustays']
  los                   double   [note: 'from icustays']

  all_vanco_charttime  datetime [note: 'from all_vanco']
  all_vanco_value      varchar  [note: 'from all_vanco']
  all_vanco_valuenum   double   [note: 'from all_vanco']
  all_vanco_valueuom   varchar  [note: 'from all_vanco']
  all_vanco_flag       varchar  [note: 'from all_vanco']

  chartevents_2999_col   data  [note: 'from chartevents']

  diag_n             integer  [note: 'from diagnoses_icd']
  diag_codes         varchar  [note: 'from diagnoses_icd']
  diag_descs         integer  [note: 'from d_icd_diagnoses']
  primary_diag_code  integer  [note: 'from diagnoses_icd']
  primary_diag_desc  integer  [note: 'from d_icd_diagnoses']
  diag_1_code        integer  [note: 'from diagnoses_icd']
  diag_2_code        integer  [note: 'from diagnoses_icd']
  diag_3_code        integer  [note: 'from diagnoses_icd']
  diag_4_code        integer  [note: 'from diagnoses_icd']
  diag_5_code        integer  [note: 'from diagnoses_icd']
  diag_1_desc        integer  [note: 'from d_icd_diagnoses']
  diag_2_desc        integer  [note: 'from d_icd_diagnoses']
  diag_3_desc        integer  [note: 'from d_icd_diagnoses']
  diag_4_desc        integer  [note: 'from d_icd_diagnoses']
  diag_5_desc        integer  [note: 'from d_icd_diagnoses']

  proc_count           integer  [note: 'from procedures_icd']
  last_proc_charttime  datetime [note: 'from procedures_icd']
  proc_codes           varchar  [note: 'from procedures_icd']
  proc_titles          integer  [note: 'from d_icd_procedures']

  drg_severity_max        varchar [note: 'from drgcodes']
  drg_mortality_max       varchar [note: 'from drgcodes']
  drg_type_chosen         text    [note: 'from drgcodes']
  drg_code_chosen         double  [note: 'from drgcodes']
  drg_description_chosen  double  [note: 'from drgcodes']
  drg_severity_chosen     double  [note: 'from drgcodes']
  drg_mortality_chosen    double  [note: 'from drgcodes']

  transfers_eventtype    integer  [note: 'from transfers']
  transfers_careunit     varchar  [note: 'from transfers']
  transfers_intime       varchar  [note: 'from transfers']
  transfers_outtime      datetime [note: 'from transfers']
  services_prev_service  datetime [note: 'from services']
  services_curr_service  varchar  [note: 'from services']
  services_transfertime  varchar  [note: 'from services']

  presc_orders_count    varchar  [note: 'from prescriptions']
  presc_first_start     varchar  [note: 'from prescriptions']
  presc_last_stop       varchar  [note: 'from prescriptions']
  presc_last_drug       varchar  [note: 'from prescriptions']
  presc_last_route      varchar  [note: 'from prescriptions']
  presc_max_dose        varchar  [note: 'from prescriptions']
  presc_max_strength    varchar  [note: 'from prescriptions']
  presc_doses_per_24h   varchar  [note: 'from prescriptions']
  pharm_dispense_count  varchar  [note: 'from pharmacy']
  pharm_first_start     varchar  [note: 'from pharmacy']
  pharm_last_stop       varchar  [note: 'from pharmacy']
  pharm_last_med        varchar  [note: 'from pharmacy']
  pharm_last_route      varchar  [note: 'from pharmacy']
  pharm_max_fill_qty    varchar  [note: 'from pharmacy']
  emar_events_count     varchar  [note: 'from emar']
  emar_admin_count      varchar  [note: 'from emar']
  emar_last_event       varchar  [note: 'from emar']
  emar_last_med         varchar  [note: 'from emar']
  emar_last_charttime   varchar  [note: 'from emar']

  microevent_id_datetime       integer  [note: 'from datetimeevents']
  micro_specimen_id_datetime   integer  [note: 'from datetimeevents']
  order_provider_id_datetime   varchar  [note: 'from datetimeevents']
  chartdate_datetime           datetime [note: 'from datetimeevents']
  charttime_datetime           datetime [note: 'from datetimeevents']
  spec_itemid_datetime         integer  [note: 'from datetimeevents']
  spec_type_desc_datetime      varchar  [note: 'from datetimeevents']
  test_seq_datetime            integer  [note: 'from datetimeevents']
  storedate_datetime           datetime [note: 'from datetimeevents']
  storetime_datetime           datetime [note: 'from datetimeevents']
  test_itemid_datetime         integer  [note: 'from datetimeevents']
  test_name_datetime           varchar  [note: 'from datetimeevents']
  org_itemid_datetime          integer  [note: 'from datetimeevents']
  org_name_datetime            varchar  [note: 'from datetimeevents']
  isolate_num_datetime         integer  [note: 'from datetimeevents']
  quantity_datetime            double   [note: 'from datetimeevents']
  ab_itemid_datetime           integer  [note: 'from datetimeevents']
  ab_name_datetime             varchar  [note: 'from datetimeevents']
  dilution_text_datetime       varchar  [note: 'from datetimeevents']
  dilution_comparison_datetime varchar  [note: 'from datetimeevents']
  dilution_value_datetime      varchar  [note: 'from datetimeevents']
  interpretation_datetime      varchar  [note: 'from datetimeevents']
  comments_datetime            text     [note: 'from datetimeevents']

  caregiver_id_ingredient    integer  [note: 'from ingredientevents']
  starttime_ingredient       datetime [note: 'from ingredientevents']
  endtime_ingredient         datetime [note: 'from ingredientevents']
  storetime_ingredient       datetime [note: 'from ingredientevents']
  itemid_ingredient          integer  [note: 'from ingredientevents']
  amount_ingredient          double   [note: 'from ingredientevents']
  amountuom_ingredient       varchar  [note: 'from ingredientevents']
  rate_ingredient            double   [note: 'from ingredientevents']
  rateuom_ingredient         varchar  [note: 'from ingredientevents']
  orderid_ingredient         integer  [note: 'from ingredientevents']
  linkorderid_ingredient     integer  [note: 'from ingredientevents']
  statusdescription_ingredient varchar [note: 'from ingredientevents']
  originalamount_ingredient   double  [note: 'from ingredientevents']
  originalrate_ingredient     double  [note: 'from ingredientevents']

  caregiver_id_input    integer  [note: 'from inputevents']
  starttime_input       datetime [note: 'from inputevents']
  endtime_input         datetime [note: 'from inputevents']
  storetime_input       datetime [note: 'from inputevents']
  itemid_input          integer  [note: 'from inputevents']
  amount_input          double   [note: 'from inputevents']
  amountuom_input       varchar  [note: 'from inputevents']
  rate_input            double   [note: 'from inputevents']
  rateuom_input         varchar  [note: 'from inputevents']
  orderid_input         integer  [note: 'from inputevents']
  linkorderid_input     integer  [note: 'from inputevents']
  ordercategoryname_input            varchar [note: 'from inputevents']
  secondaryordercategoryname_input   varchar [note: 'from inputevents']
  ordercomponenttypedescription_input varchar [note: 'from inputevents']
  ordercategorydescription_input      varchar [note: 'from inputevents']
  patientweight_input    double   [note: 'from inputevents']
  totalamount           double   [note: 'from inputevents']
  totalamountuom        varchar  [note: 'from inputevents']
  isopenbag_input       integer  [note: 'from inputevents']
  continueinnextdept_input integer [note: 'from inputevents']
  statusdescription_input varchar [note: 'from inputevents']
  originalamount_input   double   [note: 'from inputevents']
  originalrate_input     double   [note: 'from inputevents']
  doses_per_24_hrs_input double   [note: 'from inputevents']

  microevent_id_micro       integer  [note: 'from microbiologyevents']
  micro_specimen_id_micro   integer  [note: 'from microbiologyevents']
  order_provider_id_micro   varchar  [note: 'from microbiologyevents']
  chartdate_micro           datetime [note: 'from microbiologyevents']
  charttime_micro           datetime [note: 'from microbiologyevents']
  spec_itemid_micro         integer  [note: 'from microbiologyevents']
  spec_type_desc_micro      varchar  [note: 'from microbiologyevents']
  test_seq_micro            integer  [note: 'from microbiologyevents']
  storedate_micro           datetime [note: 'from microbiologyevents']
  storetime_micro           datetime [note: 'from microbiologyevents']
  test_itemid_micro         integer  [note: 'from microbiologyevents']
  test_name_micro           varchar  [note: 'from microbiologyevents']
  org_itemid_micro          integer  [note: 'from microbiologyevents']
  org_name_micro            varchar  [note: 'from microbiologyevents']
  isolate_num_micro         integer  [note: 'from microbiologyevents']
  quantity_micro            double   [note: 'from microbiologyevents']
  ab_itemid_micro           integer  [note: 'from microbiologyevents']
  ab_name_micro             varchar  [note: 'from microbiologyevents']
  dilution_text_micro       varchar  [note: 'from microbiologyevents']
  dilution_comparison_micro varchar  [note: 'from microbiologyevents']
  dilution_value_micro      varchar  [note: 'from microbiologyevents']
  interpretation_micro      varchar  [note: 'from microbiologyevents']
  comments_micro            text     [note: 'from microbiologyevents']

  itemid_other_labs   integer  [note: 'from other_labs_raw']
  charttime_other_labs datetime [note: 'from other_labs_raw']
  value_other_labs    varchar  [note: 'from other_labs_raw']
  valuenum_other_labs double   [note: 'from other_labs_raw']
  valueuom_other_labs varchar  [note: 'from other_labs_raw']
  flag_other_labs     varchar  [note: 'from other_labs_raw']

  caregiver_id_output    integer  [note: 'from outputevents']
  charttime_output       datetime [note: 'from outputevents']
  storetime_output       datetime [note: 'from outputevents']
  itemid_output          integer  [note: 'from outputevents']
  value_output           varchar  [note: 'from outputevents']
  valueuom_output        varchar  [note: 'from outputevents']

  poe_id_poe          varchar [note: 'from poe']
  poe_seq_poe         integer [note: 'from poe']
  ordertime_poe       datetime [note: 'from poe']
  order_type_poe      varchar [note: 'from poe']
  order_subtype_poe   varchar [note: 'from poe']
  transaction_type_poe varchar [note: 'from poe']
  discontinue_of_poe_id_poe varchar [note: 'from poe']
  discontinued_by_poe_id_poe varchar [note: 'from poe']
  order_provider_id_poe varchar [note: 'from poe']
  order_status_poe    varchar [note: 'from poe']

  caregiver_id_procedure         integer [note: 'from procedureevents']
  starttime_procedure            datetime [note: 'from procedureevents']
  endtime_procedure              datetime [note: 'from procedureevents']
  storetime_procedure            datetime [note: 'from procedureevents']
  itemid_procedure               integer [note: 'from procedureevents']
  value_procedure               varchar [note: 'from procedureevents']
  valueuom_procedure            varchar [note: 'from procedureevents']
  location_procedure            varchar [note: 'from procedureevents']
  locationcategory_procedure    varchar [note: 'from procedureevents']
  orderid_procedure             integer [note: 'from procedureevents']
  linkorderid_procedure         integer [note: 'from procedureevents']
  ordercategoryname_procedure   varchar [note: 'from procedureevents']
  ordercategorydescription_procedure varchar [note: 'from procedureevents']
  patientweight_procedure        double [note: 'from procedureevents']
  isopenbag_procedure            integer [note: 'from procedureevents']
  continueinnextdept_procedure   integer [note: 'from procedureevents']
  statusdescription_procedure    varchar [note: 'from procedureevents']
  originalamount_procedure       double  [note: 'from procedureevents']
  originalrate_procedure         double  [note: 'from procedureevents']

  //////////////////////
  // ستون‌های اضافه‌شده از جدول patients (فقط مهم‌ها)
  //////////////////////
  dob_patient         date     [note: 'date of birth from patients (may be shifted in MIMIC)']
  gender_patient      varchar  [note: 'from patients']
  age_at_admit        integer  [note: 'floor(years) at admittime; derived: admittime - dob_patient']

  //////////////////////
  // ستون‌های اضافه‌شده از caregivers (فقط برچسب/نام کاربردی)
  //////////////////////
  caregiver_label_ingredient    varchar [note: 'label/role lookup for caregiver_id_ingredient (from caregivers)']
  caregiver_label_input         varchar [note: 'label/role lookup for caregiver_id_input (from caregivers)']
  caregiver_label_output        varchar [note: 'label/role lookup for caregiver_id_output (from caregivers)']
  caregiver_label_procedure     varchar [note: 'label/role lookup for caregiver_id_procedure (from caregivers)']
  caregiver_label_emar          varchar [note: 'label/role lookup for pharmacy_id_emar or caregiver if available']

  //////////////////////
  // ستون‌های اضافه‌شده از دیکشنری d_icd_diagnoses (توضیحات کد)
  //////////////////////
  icd_description_diagnoses     varchar [note: 'long_title mapping for icd_code_diagnoses from d_icd_diagnoses']
  icd_description_procedures    varchar [note: 'long_title mapping for icd_code_procedures from d_icd_procedures']

  //////////////////////
  // ستون‌های اضافه‌شده از HCPCS / hcpcsevents (فقط کد/توضیح کاربردی)
  //////////////////////
  hcpcs_code_event              varchar [note: 'HCPCS/CPT-like code if present (from hcpcsevents / d_hcpcs)']
  hcpcs_description_event       varchar [note: 'human-readable description for hcpcs_code_event (from d_hcpcs)']

  indexes {
    (subject_id, hadm_id, day_index) [pk]  // تعریف کلید اصلی مرکب:contentReference[oaicite:2]{index=2}
  }
}
