Table merged_table_admission_day {
  subject_id        integer    [pk]                             // کلید بیمار
  hadm_id           integer    [pk]                             // کلید بستری بیمار
  day_index         integer    [pk, note: 'شاخص روز در بستری (از روز اول: 0)']

  admittime         datetime   [note: 'from admissions']
  dischtime         datetime   [note: 'from admissions']
  deathtime         datetime   [note: 'from admissions']
  admission_type    varchar    [note: 'from admissions']
  admit_provider_id varchar    [note: 'from admissions']
  admission_location varchar   [note: 'from admissions']
  discharge_location varchar  [note: 'from admissions']
  insurance         varchar    [note: 'from admissions']
  language          varchar    [note: 'from admissions']
  marital_status    varchar    [note: 'from admissions']
  race              varchar    [note: 'from admissions']
  edregtime         datetime   [note: 'from admissions']
  edouttime         datetime   [note: 'from admissions']
  hospital_expire_flag integer [note: 'from admissions']

  stay_id               integer  [note: 'from icustays']
  first_careunit        varchar  [note: 'from icustays']
  last_careunit         varchar  [note: 'from icustays']
  icustays_intime       datetime [note: 'from icustays']
  icustays_outtime      datetime [note: 'from icustays']
  los                   double   [note: 'from icustays']

  all_vanco_itemid     integer  [note: 'from all_vanco']
  all_vanco_charttime  datetime [note: 'from all_vanco']
  all_vanco_value      varchar  [note: 'from all_vanco']
  all_vanco_valuenum   double   [note: 'from all_vanco']
  all_vanco_valueuom   varchar  [note: 'from all_vanco']
  all_vanco_flag       varchar  [note: 'from all_vanco']

  charttime_chartevents datetime [note: 'from chartevents']
  itemid_chartevents    integer  [note: 'from chartevents']
  value_chartevents     varchar  [note: 'from chartevents']
  valuenum_chartevents  double   [note: 'from chartevents']
  valueuom_chartevents  varchar  [note: 'from chartevents']
  warning_chartevents   varchar  [note: 'from chartevents']

  microevent_id_datetime       integer  [note: 'from datetimeevents']
  micro_specimen_id_datetime   integer  [note: 'from datetimeevents']
  order_provider_id_datetime   varchar  [note: 'from datetimeevents']
  chartdate_datetime           datetime [note: 'from datetimeevents']
  charttime_datetime           datetime [note: 'from datetimeevents']
  spec_itemid_datetime         integer  [note: 'from datetimeevents']
  spec_type_desc_datetime      varchar  [note: 'from datetimeevents']
  test_seq_datetime            integer  [note: 'from datetimeevents']
  storedate_datetime           datetime [note: 'from datetimeevents']
  storetime_datetime           datetime [note: 'from datetimeevents']
  test_itemid_datetime         integer  [note: 'from datetimeevents']
  test_name_datetime           varchar  [note: 'from datetimeevents']
  org_itemid_datetime          integer  [note: 'from datetimeevents']
  org_name_datetime            varchar  [note: 'from datetimeevents']
  isolate_num_datetime         integer  [note: 'from datetimeevents']
  quantity_datetime            double   [note: 'from datetimeevents']
  ab_itemid_datetime           integer  [note: 'from datetimeevents']
  ab_name_datetime             varchar  [note: 'from datetimeevents']
  dilution_text_datetime       varchar  [note: 'from datetimeevents']
  dilution_comparison_datetime varchar  [note: 'from datetimeevents']
  dilution_value_datetime      varchar  [note: 'from datetimeevents']
  interpretation_datetime      varchar  [note: 'from datetimeevents']
  comments_datetime            text     [note: 'from datetimeevents']

  seq_num_diagnoses       integer  [note: 'from diagnoses_icd']
  icd_code_diagnoses      varchar  [note: 'from diagnoses_icd']
  icd_version_diagnoses   integer  [note: 'from diagnoses_icd']

  drg_type               varchar [note: 'from drgcodes']
  drg_code               varchar [note: 'from drgcodes']
  description_drg        text    [note: 'from drgcodes']
  drg_severity           double  [note: 'from drgcodes']
  drg_mortality          double  [note: 'from drgcodes']

  pharmacy_id_emar      integer  [note: 'from emar']
  charttime_emar        datetime [note: 'from emar']
  medication_emar       text     [note: 'from emar']
  event_txt_emar        text     [note: 'from emar']

  caregiver_id_ingredient    integer  [note: 'from ingredientevents']
  starttime_ingredient       datetime [note: 'from ingredientevents']
  endtime_ingredient         datetime [note: 'from ingredientevents']
  storetime_ingredient       datetime [note: 'from ingredientevents']
  itemid_ingredient          integer  [note: 'from ingredientevents']
  amount_ingredient          double   [note: 'from ingredientevents']
  amountuom_ingredient       varchar  [note: 'from ingredientevents']
  rate_ingredient            double   [note: 'from ingredientevents']
  rateuom_ingredient         varchar  [note: 'from ingredientevents']
  orderid_ingredient         integer  [note: 'from ingredientevents']
  linkorderid_ingredient     integer  [note: 'from ingredientevents']
  statusdescription_ingredient varchar [note: 'from ingredientevents']
  originalamount_ingredient   double  [note: 'from ingredientevents']
  originalrate_ingredient     double  [note: 'from ingredientevents']

  caregiver_id_input    integer  [note: 'from inputevents']
  starttime_input       datetime [note: 'from inputevents']
  endtime_input         datetime [note: 'from inputevents']
  storetime_input       datetime [note: 'from inputevents']
  itemid_input          integer  [note: 'from inputevents']
  amount_input          double   [note: 'from inputevents']
  amountuom_input       varchar  [note: 'from inputevents']
  rate_input            double   [note: 'from inputevents']
  rateuom_input         varchar  [note: 'from inputevents']
  orderid_input         integer  [note: 'from inputevents']
  linkorderid_input     integer  [note: 'from inputevents']
  ordercategoryname_input            varchar [note: 'from inputevents']
  secondaryordercategoryname_input   varchar [note: 'from inputevents']
  ordercomponenttypedescription_input varchar [note: 'from inputevents']
  ordercategorydescription_input      varchar [note: 'from inputevents']
  patientweight_input    double   [note: 'from inputevents']
  totalamount           double   [note: 'from inputevents']
  totalamountuom        varchar  [note: 'from inputevents']
  isopenbag_input       integer  [note: 'from inputevents']
  continueinnextdept_input integer [note: 'from inputevents']
  statusdescription_input varchar [note: 'from inputevents']
  originalamount_input   double   [note: 'from inputevents']
  originalrate_input     double   [note: 'from inputevents']
  doses_per_24_hrs_input double   [note: 'from inputevents']

  microevent_id_micro       integer  [note: 'from microbiologyevents']
  micro_specimen_id_micro   integer  [note: 'from microbiologyevents']
  order_provider_id_micro   varchar  [note: 'from microbiologyevents']
  chartdate_micro           datetime [note: 'from microbiologyevents']
  charttime_micro           datetime [note: 'from microbiologyevents']
  spec_itemid_micro         integer  [note: 'from microbiologyevents']
  spec_type_desc_micro      varchar  [note: 'from microbiologyevents']
  test_seq_micro            integer  [note: 'from microbiologyevents']
  storedate_micro           datetime [note: 'from microbiologyevents']
  storetime_micro           datetime [note: 'from microbiologyevents']
  test_itemid_micro         integer  [note: 'from microbiologyevents']
  test_name_micro           varchar  [note: 'from microbiologyevents']
  org_itemid_micro          integer  [note: 'from microbiologyevents']
  org_name_micro            varchar  [note: 'from microbiologyevents']
  isolate_num_micro         integer  [note: 'from microbiologyevents']
  quantity_micro            double   [note: 'from microbiologyevents']
  ab_itemid_micro           integer  [note: 'from microbiologyevents']
  ab_name_micro             varchar  [note: 'from microbiologyevents']
  dilution_text_micro       varchar  [note: 'from microbiologyevents']
  dilution_comparison_micro varchar  [note: 'from microbiologyevents']
  dilution_value_micro      varchar  [note: 'from microbiologyevents']
  interpretation_micro      varchar  [note: 'from microbiologyevents']
  comments_micro            text     [note: 'from microbiologyevents']

  itemid_other_labs   integer  [note: 'from other_labs_raw']
  charttime_other_labs datetime [note: 'from other_labs_raw']
  value_other_labs    varchar  [note: 'from other_labs_raw']
  valuenum_other_labs double   [note: 'from other_labs_raw']
  valueuom_other_labs varchar  [note: 'from other_labs_raw']
  flag_other_labs     varchar  [note: 'from other_labs_raw']

  caregiver_id_output    integer  [note: 'from outputevents']
  charttime_output       datetime [note: 'from outputevents']
  storetime_output       datetime [note: 'from outputevents']
  itemid_output          integer  [note: 'from outputevents']
  value_output           varchar  [note: 'from outputevents']
  valueuom_output        varchar  [note: 'from outputevents']

  pharmacy_id_pharmacy     integer [note: 'from pharmacy']
  poe_id_pharmacy          varchar [note: 'from pharmacy']
  starttime_pharmacy       datetime [note: 'from pharmacy']
  stoptime_pharmacy        datetime [note: 'from pharmacy']
  medication_pharmacy      text    [note: 'from pharmacy']
  proc_type_pharmacy       varchar [note: 'from pharmacy']
  status_pharmacy          varchar [note: 'from pharmacy']
  entertime_pharmacy       datetime [note: 'from pharmacy']
  verifiedtime_pharmacy    datetime [note: 'from pharmacy']
  route_pharmacy           varchar [note: 'from pharmacy']
  frequency_pharmacy       varchar [note: 'from pharmacy']
  disp_sched_pharmacy      varchar [note: 'from pharmacy']
  infusion_type_pharmacy   varchar [note: 'from pharmacy']
  sliding_scale_pharmacy   varchar [note: 'from pharmacy']
  lockout_interval_pharmacy varchar [note: 'from pharmacy']
  basal_rate_pharmacy      double [note: 'from pharmacy']
  one_hr_max_pharmacy      double [note: 'from pharmacy']
  doses_per_24_hrs_pharmacy double [note: 'from pharmacy']
  duration_pharmacy        double [note: 'from pharmacy']
  duration_interval_pharmacy varchar [note: 'from pharmacy']
  expiration_value_pharmacy double [note: 'from pharmacy']
  expiration_unit_pharmacy varchar [note: 'from pharmacy']
  expirationdate_pharmacy  datetime [note: 'from pharmacy']
  dispensation_pharmacy    varchar [note: 'from pharmacy']
  fill_quantity_pharmacy   double  [note: 'from pharmacy']

  poe_id_poe          varchar [note: 'from poe']
  poe_seq_poe         integer [note: 'from poe']
  ordertime_poe       datetime [note: 'from poe']
  order_type_poe      varchar [note: 'from poe']
  order_subtype_poe   varchar [note: 'from poe']
  transaction_type_poe varchar [note: 'from poe']
  discontinue_of_poe_id_poe varchar [note: 'from poe']
  discontinued_by_poe_id_poe varchar [note: 'from poe']
  order_provider_id_poe varchar [note: 'from poe']
  order_status_poe    varchar [note: 'from poe']

  pharmacy_id_prescriptions integer [note: 'from prescriptions']
  poe_id_prescriptions       varchar [note: 'from prescriptions']
  poe_seq_prescriptions      integer [note: 'from prescriptions']
  order_provider_id_prescriptions varchar [note: 'from prescriptions']
  starttime_prescriptions    datetime [note: 'from prescriptions']
  stoptime_prescriptions     datetime [note: 'from prescriptions']
  drug_type                 varchar [note: 'from prescriptions']
  drug                      varchar [note: 'from prescriptions']
  formulary_drug_cd         varchar [note: 'from prescriptions']
  gsn                       double  [note: 'from prescriptions']
  ndc                       double  [note: 'from prescriptions']
  prod_strength             varchar [note: 'from prescriptions']
  form_rx                   varchar [note: 'from prescriptions']
  dose_val_rx               double  [note: 'from prescriptions']
  dose_unit_rx              varchar [note: 'from prescriptions']
  form_val_disp             varchar [note: 'from prescriptions']
  form_unit_disp            varchar [note: 'from prescriptions']
  doses_per_24_hrs_prescriptions double [note: 'from prescriptions']
  route_prescriptions       varchar [note: 'from prescriptions']

  caregiver_id_procedure         integer [note: 'from procedureevents']
  starttime_procedure            datetime [note: 'from procedureevents']
  endtime_procedure              datetime [note: 'from procedureevents']
  storetime_procedure            datetime [note: 'from procedureevents']
  itemid_procedure               integer [note: 'from procedureevents']
  value_procedure               varchar [note: 'from procedureevents']
  valueuom_procedure            varchar [note: 'from procedureevents']
  location_procedure            varchar [note: 'from procedureevents']
  locationcategory_procedure    varchar [note: 'from procedureevents']
  orderid_procedure             integer [note: 'from procedureevents']
  linkorderid_procedure         integer [note: 'from procedureevents']
  ordercategoryname_procedure   varchar [note: 'from procedureevents']
  ordercategorydescription_procedure varchar [note: 'from procedureevents']
  patientweight_procedure        double [note: 'from procedureevents']
  isopenbag_procedure            integer [note: 'from procedureevents']
  continueinnextdept_procedure   integer [note: 'from procedureevents']
  statusdescription_procedure    varchar [note: 'from procedureevents']
  originalamount_procedure       double  [note: 'from procedureevents']
  originalrate_procedure         double  [note: 'from procedureevents']

  seq_num_procedures        integer [note: 'from procedures_icd']
  chartdate_procedures      datetime [note: 'from procedures_icd']
  icd_code_procedures       varchar  [note: 'from procedures_icd']
  icd_version_procedures    integer  [note: 'from procedures_icd']

  transfertime_services     datetime [note: 'from services']
  prev_service_services     varchar  [note: 'from services']
  curr_service_services     varchar  [note: 'from services']

  transfer_id               integer  [note: 'from transfers']
  eventtype                 varchar  [note: 'from transfers']
  careunit                  varchar  [note: 'from transfers']
  intime_transfers          datetime [note: 'from transfers']
  outtime_transfers         datetime [note: 'from transfers']

  //////////////////////
  // ستون‌های اضافه‌شده از جدول patients (فقط مهم‌ها)
  //////////////////////
  dob_patient         date     [note: 'date of birth from patients (may be shifted in MIMIC)']
  gender_patient      varchar  [note: 'from patients']
  age_at_admit        integer  [note: 'floor(years) at admittime; derived: admittime - dob_patient']

  //////////////////////
  // ستون‌های اضافه‌شده از caregivers (فقط برچسب/نام کاربردی)
  //////////////////////
  caregiver_label_ingredient    varchar [note: 'label/role lookup for caregiver_id_ingredient (from caregivers)']
  caregiver_label_input         varchar [note: 'label/role lookup for caregiver_id_input (from caregivers)']
  caregiver_label_output        varchar [note: 'label/role lookup for caregiver_id_output (from caregivers)']
  caregiver_label_procedure     varchar [note: 'label/role lookup for caregiver_id_procedure (from caregivers)']
  caregiver_label_emar          varchar [note: 'label/role lookup for pharmacy_id_emar or caregiver if available']

  //////////////////////
  // ستون‌های اضافه‌شده از دیکشنری d_icd_diagnoses (توضیحات کد)
  //////////////////////
  icd_description_diagnoses     varchar [note: 'long_title mapping for icd_code_diagnoses from d_icd_diagnoses']
  icd_description_procedures    varchar [note: 'long_title mapping for icd_code_procedures from d_icd_procedures']

  //////////////////////
  // ستون‌های اضافه‌شده از HCPCS / hcpcsevents (فقط کد/توضیح کاربردی)
  //////////////////////
  hcpcs_code_event              varchar [note: 'HCPCS/CPT-like code if present (from hcpcsevents / d_hcpcs)']
  hcpcs_description_event       varchar [note: 'human-readable description for hcpcs_code_event (from d_hcpcs)']

  indexes {
    (subject_id, hadm_id, day_index) [pk]  // تعریف کلید اصلی مرکب:contentReference[oaicite:2]{index=2}
  }
}
